---
# Backend deployment patches for staging
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-news-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: DEBUG
          value: "true"
        - name: API_WORKERS
          value: "2"
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
# Frontend deployment patches for staging
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-news-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: NODE_ENV
          value: "staging"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api-staging.fake-news-platform.com"
        - name: NEXT_PUBLIC_ENVIRONMENT
          value: "staging"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"