apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fake-news-production

# Base configuration to build upon
bases:
- ../base

# Namespace for production environment
namespace: fakenews-production

# Common labels for all production resources
commonLabels:
  environment: production
  app: fake-news-game-theory

# Prefix for resource names
namePrefix: prod-

# Resource modifications for production
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- ingress-patch.yaml
- hpa-patch.yaml

# ConfigMap generator for production
configMapGenerator:
- name: production-config
  literals:
  - environment=production
  - log_level=INFO
  - api_workers=4
  - enable_debug=false
  - max_connections=200
  - cache_ttl=7200

# Production scaling
replicas:
- name: fake-news-backend
  count: 5
- name: fake-news-frontend
  count: 3

# Production images with specific versions
images:
- name: fake-news-backend
  newTag: v1.2.0
- name: fake-news-frontend
  newTag: v1.2.0

# Resource patches for production
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: fake-news-backend
  path: production-resources-patch.yaml

- target:
    group: v1
    kind: Service
    name: fake-news-backend-service
  path: service-annotations-patch.yaml