version: '3.8'

# Development Docker Compose Override Configuration
# =================================================
#
# This file extends the base docker-compose.yml for development use.
# It provides hot-reload, local code mounting, debug tools, and
# development-friendly configurations.
#
# Usage:
#   docker-compose -f config/docker-compose.yml -f config/docker-compose.dev.yml up --build
#
# Key development features:
# - Hot-reload for both frontend and backend
# - Local source code mounting
# - Debug mode enabled
# - Exposed database/redis ports for local access
# - Development environment variables

services:
  # =======================
  # Frontend Development Overrides
  # =======================
  frontend:
    volumes:
      # Mount local source code for hot-reload
      - ../frontend:/app
      # Prevent overwriting node_modules in container
      - /app/node_modules
    command: npm run dev  # Next.js development server with hot-reload
    environment:
      # Development-specific environment variables
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
      - NODE_ENV=development

  # =======================
  # Backend Development Overrides
  # =======================
  backend:
    volumes:
      # Mount local source code for hot-reload
      - ../backend:/app
      # Share ML models directory for development
      - ../data/models:/app/models
    # FastAPI with auto-reload on file changes
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      # Development database connection
      - DATABASE_URL=postgresql://postgres:fakenews_secure_password@db:5432/fakenews_db
      - REDIS_URL=redis://redis:6379/0
      # Debug and development settings
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
      # ML development settings
      - ML_MODEL_PATH=/app/models
      - HUGGINGFACE_CACHE_DIR=/app/cache/huggingface
      # Game Theory development settings
      - SIMULATION_WORKERS=2  # Fewer workers for development
      - MAX_SIMULATION_TIME=60  # Shorter timeout for dev testing

  # =======================
  # Database Development Overrides
  # =======================
  db:
    ports:
      - "5433:5432"  # Expose for local development access (different port to avoid conflicts)

  # =======================
  # Redis Development Overrides
  # =======================
  redis:
    ports:
      - "6380:6379"  # Expose for debugging (different port to avoid conflicts)