name: Security Scanning

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: "0 3 * * 0" # weekly Sunday scan
  workflow_dispatch:

jobs:
  python-security:
    name: Python Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements-ci.txt bandit safety

      - name: Run Bandit (Python static analysis)
        run: |
          cd backend
          bandit -r app -lll

      - name: Run Safety (Dependency vulnerability check)
        run: |
          cd backend
          safety check -r requirements-ci.txt --full-report

  node-security:
    name: Node.js Security Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Run ESLint Security Plugin
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  docker-security:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Docker image
        run: |
          docker build -t local/fakenews-backend:test ./backend

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: image
          image-ref: "local/fakenews-backend:test"
          format: table
          exit-code: 0
          ignore-unfixed: true

  secrets-scan:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml